Wba.PE1.Webshop.Web/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using pe1.Webshop.Domain;
using pe1.Webshop.Web.ViewModels;

namespace pe1.Webshop.Web.Controllers
{
    public class CategoriesController : Controller
    {

        private readonly CategoryRepository categoryRepository;
        private readonly ItemRepository itemRepository;

        public CategoriesController()
        {
            categoryRepository = new CategoryRepository();
            itemRepository = new ItemRepository();

        }

        [Route("categories")]
        [Route("categories/index")]
        [Route("categories/all")]

        public IActionResult Index()
        {
            var viewModel = new CategoriesIndexVm();
            viewModel.Categories = categoryRepository.GetCategories();

            return View(viewModel);
        }



        [Route("categories/{id}")]
        public IActionResult ShowCategory(int id)
        {
            var category = categoryRepository.GetCategories().FirstOrDefault(c => c.Id == id);

            if (category == null) return NotFound();

            var itemCategory = itemRepository.GetItems().Where(i => i.Category.Id == id);

            var viewModel = new CategoriesDetailVm();
            viewModel.Category = category;
            viewModel.Items = itemCategory;

            return View(viewModel);
        }
    }
}

Wba.PE1.Webshop.Web/Controllers/CollectionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using pe1.Webshop.Domain;
using pe1.Webshop.Web.ViewModels;

namespace pe1.Webshop.Web.Controllers
{
    public class CollectionsController : Controller
    {
        private readonly CollectionsRepository collectionsRepository;
        private readonly ItemRepository itemRepository;

        public CollectionsController()
        {
            collectionsRepository = new CollectionsRepository();
            itemRepository = new ItemRepository();
        }

        [Route("collections")]
        [Route("collections/index")]
        [Route("collections/all")]

        public IActionResult Index()
        {
            var viewModel = new CollectionsIndexVm();
            viewModel.Collections = collectionsRepository.GetCollections();

            return View(viewModel);
        }

        [Route("collections/{id}")]
        public IActionResult ShowCollections(int id)
        {
            var collections = collectionsRepository.GetCollections().FirstOrDefault(c => c.Id == id);

            if (collections == null) return NotFound();

            var itemCollection = itemRepository.GetItems().Where(i => i.Collections.Id == id);

            var viewModel = new CollectionsDetailVm();
            viewModel.Collections = collections;
            viewModel.Items = itemCollection;

            return View(viewModel);
        }
    }
}

Wba.PE1.Webshop.Web/Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using pe1.Webshop.Domain;
using pe1.Webshop.Web.ViewModels;

namespace pe1.Webshop.Web.Controllers
{
    public class ItemsController : Controller
    {
        private readonly ItemRepository itemRepository;

        public ItemsController()
        {
            itemRepository = new ItemRepository();
        }

        [Route("items")]
        [Route("items/index")]
        [Route("items/all")]
        public IActionResult Index()
        {
            var viewModel = new ItemsIndexVm();
            viewModel.Items = itemRepository.GetItems();

            return View(viewModel);
        }

        [Route("items/{id}")]
        public IActionResult ShowItem(int id)
        {
            var item = itemRepository.GetItems().FirstOrDefault(i => i.Id == id);
            if (item == null) return NotFound();

            var viewModel = new ItemsShowItemVm();
            viewModel.Item = item;

            return View(viewModel);
        }

    }
}

Wba.PE1.Webshop.Web/Controllers/PropertyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using pe1.Webshop.Domain;
using pe1.Webshop.Web.ViewModels;

namespace pe1.Webshop.Web.Controllers
{
    public class PropertyController : Controller
    {

        private readonly PropertyRepository propertyRepository;
        private readonly ItemRepository itemRepository;

        public PropertyController()
        {
            propertyRepository = new PropertyRepository();
            itemRepository = new ItemRepository();
        }

       
            [Route("properties")]
            [Route("properties/index")]
            [Route("properties/all")]

            public IActionResult Index()
            {
                var viewModel = new PropertyIndexVm();
                viewModel.Properties = propertyRepository.GetProperties();

                return View(viewModel);
            }

        [Route("properties/{id}")]
        public IActionResult ShowProperty(int id)
        {
            var property = propertyRepository.GetProperties().FirstOrDefault(c => c.Id == id);

            if (property == null) return NotFound();

            var itemProperty = itemRepository.GetItems().Where(i => i.Property.Id == id);

            var viewModel = new PropertyDetailVm();
            viewModel.Property = property;
            viewModel.Items = itemProperty;

            return View(viewModel);
        }

    }
    }

Wba.PE1.Webshop.Web/Views/Shared/FooterPartial.cshtml
<div class="container-fluid bg-secondary text-dark mt-5 pt-5">
    <div class="row px-xl-5 pt-5">
        <div class="col-lg-4 col-md-12 mb-5 pr-3 pr-xl-5">
            <a href="" class="text-decoration-none">
                <h1 class="mb-4 display-5 font-weight-semi-bold"><span class="text-primary font-weight-bold border border-white px-3 mr-1">E</span>FancyFamily</h1>
            </a>
            
            <p class="mb-2"><i class="fa fa-map-marker-alt text-primary mr-3"></i>Elisabethlaan 186, 1000 Brussel</p>
            <p class="mb-2"><i class="fa fa-envelope text-primary mr-3"></i>EFFS@familyStore.com</p>
            <p class="mb-0"><i class="fa fa-phone-alt text-primary mr-3"></i>+012 345 67890</p>
        </div>
        <div class=" col-lg-8 col-md-12">
            <div class="row">
                <div class="col-md-6 mb-5">
                    <h5 class="font-weight-bold text-dark mb-4">Quick Links</h5>
                    <div class="d-flex flex-column justify-content-start">
                        <a class="text-dark mb-2" asp-controller="Home" asp-action="Index" ><i class="fa fa-angle-right mr-2"></i>Home</a>
                        
                        <a class="text-dark mb-2" href="cart.html"><i class="fa fa-angle-right mr-2"></i>Shopping Cart</a>
                        <a class="text-dark mb-2" href="checkout.html"><i class="fa fa-angle-right mr-2"></i>Checkout</a>
                        <a class="text-dark" asp-controller="Home" asp-action="Contact" ><i class="fa fa-angle-right mr-2"></i>Contact Us</a>
                    </div>
                </div>
               
                </div>
               
            </div>
      
    </div>
    <div class="row border-top border-light mx-xl-5 py-4">
        <div class="col-md-6 px-xl-0">
            <p class="mb-md-0 text-center text-md-left text-dark">
                © <a class="text-dark font-weight-semi-bold" href="#">E Fancy Family Store</a>. 
            </p>
        </div>
        <div class="col-md-6 px-xl-0 text-center text-md-right">
            <img class="img-fluid" src="img/payments.png" alt="">
        </div>
    </div>
</div>

Wba.PE1.Webshop.Web/Views/Shared/HeaderHomePagePartial.cshtml
<div id="header-carousel" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item" style="height: 410px;">
                <img class="img-fluid" src="img/carousel-1.jpg" alt="Image">
                <div class="carousel-caption d-flex flex-column align-items-center justify-content-center">
                    <div class="p-3" style="max-width: 700px;">
                        <h4 class="text-light text-uppercase font-weight-medium mb-3">10% Off Your First Order</h4>
                        <h3 class="display-4 text-white font-weight-semi-bold mb-4">Fashionable Dress</h3>
                        <a href="" class="btn btn-light py-2 px-3">Shop Now</a>
                    </div>
                </div>
            </div>
            <div class="carousel-item active" style="height: 410px;">
                <img class="img-fluid" src="img/carousel-2.jpg" alt="Image">
                <div class="carousel-caption d-flex flex-column align-items-center justify-content-center">
                    <div class="p-3" style="max-width: 700px;">
                        <h4 class="text-light text-uppercase font-weight-medium mb-3">10% Off Your First Order</h4>
                        <h3 class="display-4 text-white font-weight-semi-bold mb-4">Reasonable Price</h3>
                        <a href="" class="btn btn-light py-2 px-3">Shop Now</a>
                    </div>
                </div>
            </div>
        </div>
        <a class="carousel-control-prev" href="#header-carousel" data-slide="prev">
            <div class="btn btn-dark" style="width: 45px; height: 45px;">
                <span class="carousel-control-prev-icon mb-n2"></span>
            </div>
        </a>
        <a class="carousel-control-next" href="#header-carousel" data-slide="next">
            <div class="btn btn-dark" style="width: 45px; height: 45px;">
                <span class="carousel-control-next-icon mb-n2"></span>
            </div>
        </a>
    </div>

Wba.PE1.Webshop.Web/Views/Shared/NavbarPartial.cshtml
<div class="container-fluid">
    <div class="row border-top px-xl-5">
        <div class="col-lg-3 d-none d-lg-block">
            <a class="btn shadow-none d-flex align-items-center justify-content-between bg-primary text-white w-100" data-toggle="collapse" href="#navbar-vertical" style="height: 65px; margin-top: -1px; padding: 0 30px;">
                <h6 class="m-0">Categories</h6>
                <i class="fa fa-angle-down text-dark"></i>
            </a>
            <nav class="collapse position-absolute navbar navbar-vertical navbar-light align-items-start p-0 border border-top-0 border-bottom-0 bg-light" id="navbar-vertical" style="width: calc(100% - 30px); z-index: 1;">
                <div class="navbar-nav w-100 overflow-hidden" style="height: 410px">
                    <div class="nav-item dropdown">

                    </div>
                    @await Component.InvokeAsync("MainNavigation")
                </div>
            </nav>
        </div>
        <div class="col-lg-9">
            <nav class="navbar navbar-expand-lg bg-light navbar-light py-3 py-lg-0 px-0">
                @await Component.InvokeAsync("TopbarNavigation")
            </nav>
        </div>
    </div>
</div>

Wba.PE1.Webshop.Web/Views/Shared/ShowAllItemsPartial.cshtml
@model pe1.Webshop.Domain.Item

<div class=" col-lg-3 col-md-6 col-sm-12 pb-1">

    <div class="card product-item border-0 mb-4">
        <img class="card-img-top" src="@Model.Img" alt="@Model.Name" style="height: 500px" />
        <div class="card-body border-left border-right text-center p-0 pt-4 pb-3">
            <h2>@Model.Name</h2>
            <p>@Model.ShortDescr.</p>
            <p>Price: @Model.Price.ToString("c")</p>

            <div class="card-footer d-flex justify-content-between bg-light border">
                <a href="@Model.Img" class="btn btn-sm text-dark p-0"><i class="fas fa-eye text-primary mr-1"></i>View Detail</a>
                <a href="" class="btn btn-sm text-dark p-0"><i class="fas fa-shopping-cart text-primary mr-1"></i>Add To Cart</a>
            </div>
            @*<p>  <a class="btn btn-warning" href="=@Model.Img">Show more</a> </p>*@
        </div>
    </div>



</div>

Wba.PE1.Webshop.Web/Views/Shared/ShowItemsPartial.cshtml
@model pe1.Webshop.Domain.Item


<div class="col-lg-4 col-md-6 col-sm-12 ">

    <div class="card product-item border-0 mb-4">

        <div class="card-header product-img position-relative overflow-hidden bg-transparent border p-0">
            <img class="img-fluid " src="@Model.Img" alt="@Model.Name">
        </div>

        <div class="card-body border-left border-right text-center p-0 pt-4 pb-3">
            <h6 class="text-truncate mb-3">@Model.Name</h6>

            <div class="d-flex justify-content-center">
                <h6>@Model.Price.ToString("c")</h6>@*<h6 class="text-muted ml-2"><del>$123.00</del></h6>*@
            </div>
        </div>

        <div class="card-footer d-flex justify-content-between bg-light border">
            <a href="@Model.Img" class="btn btn-sm text-dark p-0"><i class="fas fa-eye text-primary mr-1"></i>View Detail</a>
            <a href="" class="btn btn-sm text-dark p-0"><i class="fas fa-shopping-cart text-primary mr-1"></i>Add To Cart</a>
        </div>


    </div>
</div>

Wba.PE1.Webshop.Web/Views/Shared/TopbarPartial.cshtml
<div class="container-fluid">
    <div class="row bg-secondary py-2 px-xl-5">
        <div class="col-lg-6 d-none d-lg-block">
            <div class="d-inline-flex align-items-center">
                <a class="text-dark" href="">FAQs</a>
                <span class="text-muted px-2">|</span>
                <a class="text-dark" href="">Help</a>
                <span class="text-muted px-2">|</span>
                <a class="text-dark" href="">Support</a>
            </div>
        </div>
        <div class="col-lg-6 text-center text-lg-right">
            <div class="d-inline-flex align-items-center">
                <a class="text-dark px-2" href="">
                    <i class="fab fa-facebook-f"></i>
                </a>
                <a class="text-dark px-2" href="">
                    <i class="fab fa-twitter"></i>
                </a>
                <a class="text-dark px-2" href="">
                    <i class="fab fa-linkedin-in"></i>
                </a>
                <a class="text-dark px-2" href="">
                    <i class="fab fa-instagram"></i>
                </a>
                <a class="text-dark pl-2" href="">
                    <i class="fab fa-youtube"></i>
                </a>
            </div>
        </div>
    </div>
    <div class="row align-items-center py-3 px-xl-5">
        <div class="col-lg-3 d-none d-lg-block">
            <a href="" class="text-decoration-none">
                <h1 class="m-0 display-5 font-weight-semi-bold"><span class="text-primary font-weight-bold border px-3 mr-1">E</span>FancyFamily</h1>
            </a>
        </div>
        <div class="col-lg-6 col-6 text-left">
            <form method="get" action="">
                <div class="input-group">
                    <input  type="text" class="form-control" placeholder="Search for products">
                    <div class="input-group-append">
                        <span class="input-group-text bg-transparent text-primary">
                            <i class="fa fa-search"></i> 
                        </span>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-lg-3 col-6 text-right">
            <a href="" class="btn border">
                <i class="fas fa-heart text-primary"></i>
                <span class="badge">0</span>
            </a>
            <a href="" class="btn border">
                <i class="fas fa-shopping-cart text-primary"></i>
                <span class="badge">0</span>
            </a>
        </div>
    </div>
</div>

Wba.PE1.Webshop.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Fancy Family Store </title>

    <!-- Favicon -->
    <link href="~/bootstrap/img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&amp;display=swap" rel="stylesheet">

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="~/bootstrap/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="~/bootstrap/css/style.css" rel="stylesheet">

    <environment names="Production, Staging">
        <link rel="stylesheet" asp-append-version="true" href="" />
    </environment>
    <environment names="Development">
        <link rel="stylesheet" asp-append-version="false" href="" />
    </environment>


</head>
<body>
    <!-- Topbar Start -->
    <partial name="TopbarPartial" />
    <!-- Topbar End -->
    <!-- Navbar Start -->
    <div class="container-fluid mb-5">
        <div class="row border-top px-xl-5">

            <div class="col-lg-3 d-none d-lg-block">
                <a class="btn shadow-none d-flex align-items-center justify-content-between bg-primary text-white w-100" data-toggle="collapse" href="#navbar-vertical" style="height: 65px; margin-top: -1px; padding: 0 30px;">
                    <h6 class="m-0">Categories</h6>
                    <i class="fa fa-angle-down text-dark"></i>
                </a>
                <nav class="collapse show navbar navbar-vertical navbar-light align-items-start p-0 border border-top-0 border-bottom-0" id="navbar-vertical">
                    @await Component.InvokeAsync("MainNavigation")
                </nav>
            </div>
            <div class="col-lg-9">
                <nav class="navbar navbar-expand-lg bg-light navbar-light py-3 py-lg-0 px-0">

                    @await Component.InvokeAsync("TopbarNavigation")

                   
                </nav>


                <div id="header-carousel" class="carousel slide" data-ride="carousel">
                    <div class="carousel-inner">
                        <div class="carousel-item" style="height: 410px;">
                            <img class="img-fluid" src="~/images/pexels-anna-shvets-5325768.jpg" alt="By Anna Shvets">
                            <div class="carousel-caption d-flex flex-column align-items-center justify-content-center">
                                <div class="p-3" style="max-width: 700px;">
                                    <h4 class="text-light text-uppercase font-weight-medium mb-3">10% Off Your First Order</h4>
                                    <h3 class="display-4 text-white font-weight-semi-bold mb-4">Fashion</h3>
                                    <a asp-controller="Items" asp-action="Index"  class="btn btn-light py-2 px-3">Shop Now</a>
                                </div>
                            </div>
                        </div>
                        <div class="carousel-item active" style="height: 410px;">
                            <img class="img-fluid" src="~/images/pexels-anna-shvets-5325586.jpg" alt="By Anna Shvets">
                            <div class="carousel-caption d-flex flex-column align-items-center justify-content-center">
                                <div class="p-3" style="max-width: 700px;">
                                    <h4 class="text-light text-uppercase font-weight-medium mb-3">10% Off Your First Order</h4>
                                    <h3 class="display-4 text-white font-weight-semi-bold mb-4">Reasonable Price</h3>
                                    <a asp-controller="Property" asp-action="ShowProperty" asp-route-Id="2" class="btn btn-light py-2 px-3">Shop Now</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <a class="carousel-control-prev" href="#header-carousel" data-slide="prev">
                        <div class="btn btn-dark" style="width: 45px; height: 45px;">
                            <span class="carousel-control-prev-icon mb-n2"></span>
                        </div>
                    </a>
                    <a class="carousel-control-next" href="#header-carousel" data-slide="next">
                        <div class="btn btn-dark" style="width: 45px; height: 45px;">
                            <span class="carousel-control-next-icon mb-n2"></span>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </div>
    <!-- Navbar End -->
    <!-- Featured Start -->
    <div class="container-fluid pt-5">
        <div class="row px-xl-5 pb-3">
            <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
                <div class="d-flex align-items-center border mb-4" style="padding: 30px;">
                    <h1 class="fa fa-check text-primary m-0 mr-3"></h1>
                    <h5 class="font-weight-semi-bold m-0">Quality Product</h5>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
                <div class="d-flex align-items-center border mb-4" style="padding: 30px;">
                    <h1 class="fa fa-shipping-fast text-primary m-0 mr-2"></h1>
                    <h5 class="font-weight-semi-bold m-0">Free Shipping</h5>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
                <div class="d-flex align-items-center border mb-4" style="padding: 30px;">
                    <h1 class="fas fa-exchange-alt text-primary m-0 mr-3"></h1>
                    <h5 class="font-weight-semi-bold m-0">14-Day Return</h5>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
                <div class="d-flex align-items-center border mb-4" style="padding: 30px;">
                    <h1 class="fa fa-phone-volume text-primary m-0 mr-3"></h1>
                    <h5 class="font-weight-semi-bold m-0">24/7 Support</h5>
                </div>
            </div>
        </div>
    </div>
    <!-- Featured End -->
    <!-- Offer Start -->
    <div class="container-fluid offer pt-5">
        <div class="row px-xl-5">
            <div class="col-md-6 pb-4">
                <div class="position-relative bg-secondary text-center text-md-right text-white mb-2 py-5 px-5">
                    <img src="~/images/choose-something-new.png" alt="New">
                    <div class="position-relative" style="z-index: 1;">
                        <h5 class="text-uppercase text-primary mb-3">20% off the all order</h5>
                        <h1 class="mb-4 font-weight-semi-bold">New Collection</h1>
                        <a asp-controller="Property" asp-action="ShowProperty" asp-route-Id="1" class="btn btn-outline-primary py-md-2 px-md-3">Shop Now</a>
                    </div>
                </div>
            </div>
            <div class="col-md-6 pb-4">
                <div class="position-relative bg-secondary text-center text-md-left text-white mb-2 py-5 px-5">
                    <img src="~/images/sale-stamp.png" style="z-index:5" alt="discount">
                    <div class="position-relative" style="z-index: 1;">
                        <h5 class="text-uppercase text-primary mb-3">20% off the all order</h5>
                        <h1 class="mb-4 font-weight-semi-bold">Outlet Collection</h1>
                        <a asp-controller="Property" asp-action="ShowProperty" asp-route-Id="2" class="btn btn-outline-primary py-md-2 px-md-3">Shop Now</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Offer End -->
    <!-- Products Start -->
    <div class="container-fluid pt-5">
        <div class="text-center mb-4">
            <h2 class="section-title px-5"><span class="px-2">Trandy Products</span></h2>
        </div>
        @RenderBody()
       
    </div>
    <!-- Products End -->
    <!-- Categories Start -->
    <div class="container-fluid pt-5">
        <div class="row px-xl-5 pb-3">
            <div class="col-lg-4 col-md-6 pb-1">
                <div class="cat-item d-flex flex-column border mb-4" style="padding: 30px;">
                   
                    <a  asp-controller="Categories" asp-action="ShowCategory" asp-route-Id="1" class="cat-img position-relative overflow-hidden mb-3">
                        <img class="img-fluid" src="~/images/pexels-bruno-salvadori-2269872 - kopie.jpg" alt="By Adrian">
                    </a>
                    <h5 class="font-weight-semi-bold m-0">Men</h5>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 pb-1">
                <div class="cat-item d-flex flex-column border mb-4" style="padding: 30px;">
                    
                    <a asp-controller="Categories" asp-action="ShowCategory" asp-route-Id="2" class="cat-img position-relative overflow-hidden mb-3">
                        <img class="img-fluid" src="~/images/pexels-andrea-piacquadio-972884.jpg" alt="By Andrea Piacquadio">
                    </a>
                    <h5 class="font-weight-semi-bold m-0">Women</h5>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 pb-1">
                <div class="cat-item d-flex flex-column border mb-4" style="padding: 30px;">
                    
                    <a asp-controller="Categories" asp-action="ShowCategory" asp-route-Id="3" class="cat-img position-relative overflow-hidden mb-3">
                        <img class="img-fluid" src="~/images/pexels-allan-mas-5622350.jpg" alt="By Allan Mas">
                    </a>
                    <h5 class="font-weight-semi-bold m-0">Kids</h5>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 pb-1">
                <div class="cat-item d-flex flex-column border mb-4" style="padding: 30px;">
                   
                    <a asp-controller="Collections" asp-action="ShowCollections" asp-route-Id="1" class="cat-img position-relative overflow-hidden mb-3">
                        <img class="img-fluid" src="~/images/collis.jpg" alt="By Collis">
                    </a>
                    <h5 class="font-weight-semi-bold m-0">Accerssories</h5>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 pb-1">
                <div class="cat-item d-flex flex-column border mb-4" style="padding: 30px;">
                   
                    <a asp-controller="Collections" asp-action="ShowCollections" asp-route-Id="2" class="cat-img position-relative overflow-hidden mb-3">
                        <img class="img-fluid" src="~/images/pexels-artem-beliaikin-994517.jpg" alt="By Artem Beliakin">
                    </a>
                    <h5 class="font-weight-semi-bold m-0">Clothes</h5>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 pb-1">
                <div class="cat-item d-flex flex-column border mb-4" style="padding: 30px;">
                   
                    <a asp-controller="Collections" asp-action="ShowCollections" asp-route-Id="3" class="cat-img position-relative overflow-hidden mb-3">
                        <img class="img-fluid" src="~/images/pexels-adrian-dorobantu-2300334.jpg" alt="By Adrian Dorobantu">
                    </a>
                    <h5 class="font-weight-semi-bold m-0">Shoes</h5>
                </div>
            </div>
        </div>
    </div>
  
   
    <!-- Footer Start -->
   <partial name="FooterPartial" />
    <!-- Footer End -->
    <!-- Back to Top -->
    <a href="#" class="btn btn-primary back-to-top" style="display: none;"><i class="fa fa-angle-double-up"></i></a>


    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
    <script src="~/bootstrap/lib/easing/easing.min.js"></script>
    <script src="~/bootstrap/lib/owlcarousel/owl.carousel.min.js"></script>

    <!-- Contact Javascript File -->
    <script src="~/bootstrap/mail/jqBootstrapValidation.min.js"></script>
    <script src="~/bootstrap/mail/contact.js"></script>

    <!-- Template Javascript -->
    <script src="~/bootstrap/js/main.js"></script>



    @RenderSection("Scripts", required: false)
</body>
</html>